### ISSUE TITLE
Migrate Repo to OMS Organization

### ISSUE THREAD

**Issue by ric-evans** [Observation-Management-Service/MQClient#71]
https://github.com/Observation-Management-Service

This could also mean renaming the PyPI/pip package to `ewms-mqclient` or `oms-mqclient`--will need to look into what PyPI supports for name changes.

**Comment by dsschult** [comment]
PyPi steps:
* Create a renamed version of the package
* Publish it to PyPI under the new name
* Now create a final release under the old name which does the following:
   * Tells users about the name change
   * Depends on the new name, so anyone who runs pip install oldname will get the new name as a dependency

**Comment by ric-evans** [comment]
You are Here
